Fix write error on missing object
If PARSE_ONLY_NEW is false, the lastItemFile is not created as file, so it produces a error executing the last lines. This fix should skip that condition for avoit this error:

	Traceback (most recent call last):
	  File "parser.py", line 84, in <module>
		lastItemFile.write(str(time.mktime(lastParsedDate.utctimetuple())))
	AttributeError: 'NoneType' object has no attribute 'write'